version: '3'
services:

  db:
    image: postgres:11.4
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: [
      "bash", "-c",
      "./manage.py migrate --noinput &&
      ./manage.py runserver 0.0.0.0:8000"
    ]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
      - static:/static

volumes:
  db-data:
  static: